### ISSUE TITLE
fuzz!() never terminates

### ISSUE THREAD

**Issue by ckaran** [camshaft/bolero#13]
This may be related to #10, but I don't have a good way of verifying.

I've upgraded to bolero 0.5.0, and replaced all of the calls to `check!()` with `fuzz!()`.  Now some of my tests no longer terminate.  I've let them run overnight to see if they would eventually terminate, but they didn't.  Is there any way for me to capture some kind of output or log to attach to this bug report so you can look at it?

**Comment by camshaft** [comment]
If you could create a repo that is able to reproduce the result I can take a look at it. I don't have any debug logging at the moment so that's probably the best option.

**Comment by ckaran** [comment]
I'll see if I can, but in the meantime, here is the output from running under `lldb`:

```bash
(lldb) c
Process 29994 resuming
Process 29994 stopped
* thread #1, name = 'bit_network_lib', stop reason = signal SIGSTOP
    frame #0: 0x00007ffff77b79f3 libpthread.so.0`__pthread_cond_wait + 579
libpthread.so.0`__pthread_cond_wait:
->  0x7ffff77b79f3 <+579>: cmpq   $-0x1000, %rax            ; imm = 0xF000 
    0x7ffff77b79f9 <+585>: movq   0x30(%rsp), %r8
    0x7ffff77b79fe <+590>: ja     0x7ffff77b7b30            ; <+896>
    0x7ffff77b7a04 <+596>: movl   %r9d, %edi
(lldb) bt
* thread #1, name = 'bit_network_lib', stop reason = signal SIGSTOP
  * frame #0: 0x00007ffff77b79f3 libpthread.so.0`__pthread_cond_wait + 579
    frame #1: 0x00005555564ba1f3 bit_network_library-3f2d83c12bf05752`std::thread::park::h296acd55d5276ee3 [inlined] std::sys::unix::condvar::Condvar::wait::h1cca46687e79e674 at condvar.rs:73
    frame #2: 0x00005555564ba1f1 bit_network_library-3f2d83c12bf05752`std::thread::park::h296acd55d5276ee3 [inlined] std::sys_common::condvar::Condvar::wait::ha779a4eda9e4f92e at condvar.rs:50
    frame #3: 0x00005555564ba1f1 bit_network_library-3f2d83c12bf05752`std::thread::park::h296acd55d5276ee3 [inlined] std::sync::condvar::Condvar::wait::hb93c1601d9e8bfa5 at condvar.rs:200
    frame #4: 0x00005555564ba1d7 bit_network_library-3f2d83c12bf05752`std::thread::park::h296acd55d5276ee3 at mod.rs:919
    frame #5: 0x00005555564c3422 bit_network_library-3f2d83c12bf05752`std::sync::mpsc::blocking::WaitToken::wait::hfa37a42a6608c105 at blocking.rs:64
    frame #6: 0x0000555555ed12e2 bit_network_library-3f2d83c12bf05752`std::sync::mpsc::shared::Packet$LT$T$GT$::recv::h031a3f9382fc7f86 at shared.rs:235
    frame #7: 0x0000555555ed0426 bit_network_library-3f2d83c12bf05752`std::sync::mpsc::Receiver$LT$T$GT$::recv::hf7bff188b3bd801c at mod.rs:1179
    frame #8: 0x0000555555ee374e bit_network_library-3f2d83c12bf05752`test::console::run_tests_console::h1310f799a6a11e7c [inlined] test::run_tests::hee095da8f7fe5691 at lib.rs:323
    frame #9: 0x0000555555ee18d2 bit_network_library-3f2d83c12bf05752`test::console::run_tests_console::h1310f799a6a11e7c at console.rs:280
    frame #10: 0x0000555555eefe17 bit_network_library-3f2d83c12bf05752`test::test_main::ha4f31af3b7432712 at lib.rs:121
    frame #11: 0x0000555555ef13bc bit_network_library-3f2d83c12bf05752`test::test_main_static::h3c6293225879b233 at lib.rs:140
    frame #12: 0x0000555555cfb496 bit_network_library-3f2d83c12bf05752`bit_network_library::main::h57d110b1c895ca3b + 22
    frame #13: 0x00005555557b3b8b bit_network_library-3f2d83c12bf05752`std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h816859ff59d16966 at rt.rs:67
    frame #14: 0x00005555564c7233 bit_network_library-3f2d83c12bf05752`std::panicking::try::do_call::h0b6fc9f6090c1e2b [inlined] std::rt::lang_start_internal::_$u7b$$u7b$closure$u7d$$u7d$::h9a4aa16acf1cdc99 at rt.rs:52
    frame #15: 0x00005555564c7227 bit_network_library-3f2d83c12bf05752`std::panicking::try::do_call::h0b6fc9f6090c1e2b at panicking.rs:303
    frame #16: 0x00005555564cf4a7 bit_network_library-3f2d83c12bf05752`__rust_maybe_catch_panic at lib.rs:86
    frame #17: 0x00005555564c7d5c bit_network_library-3f2d83c12bf05752`std::rt::lang_start_internal::hcea4e704875ab132 [inlined] std::panicking::try::h9eaeeaa81242ec77 at panicking.rs:281
    frame #18: 0x00005555564c7d1e bit_network_library-3f2d83c12bf05752`std::rt::lang_start_internal::hcea4e704875ab132 [inlined] std::panic::catch_unwind::h07d504c1b691e8fb at panic.rs:394
    frame #19: 0x00005555564c7d1e bit_network_library-3f2d83c12bf05752`std::rt::lang_start_internal::hcea4e704875ab132 at rt.rs:51
    frame #20: 0x00005555557b3b67 bit_network_library-3f2d83c12bf05752`std::rt::lang_start::h2163bed54d7e6a77(main=(bit_network_library-3f2d83c12bf05752`bit_network_library::main::h57d110b1c895ca3b), argc=3, argv=0x00007fffffffdd88) at rt.rs:67
    frame #21: 0x0000555555cfb4ca bit_network_library-3f2d83c12bf05752`main + 42
    frame #22: 0x00007ffff71c2b97 libc.so.6`__libc_start_main(main=(bit_network_library-3f2d83c12bf05752`main), argc=3, argv=0x00007fffffffdd88, init=<unavailable>, fini=<unavailable>, rtld_fini=<unavailable>, stack_end=0x00007fffffffdd78) at libc-start.c:310
    frame #23: 0x00005555556598aa bit_network_library-3f2d83c12bf05752`_start + 42
(lldb)
```

I don't use conditions in my code, so that's from somewhere else.  Does `bolero` ever do anything with timed conditions?

**Comment by camshaft** [comment]
This is the output of `cargo test`, correct? All of the threading is from libtest. Can you disable that:
```
cargo test my_test -- --test-threads 1
```

**Comment by ckaran** [comment]
```bash
cargo test nodes::behaviors::trading_post::database::tests::test_distance -- --test-threads=1
```

Yields the following:

```bash
running 1 test
test nodes::behaviors::trading_post::database::tests::test_distance ... FAILED

failures:

---- nodes::behaviors::trading_post::database::tests::test_distance stdout ----
thread 'main' panicked at 'test selection must be run in threaded mode', /home/cfkaran2/.cargo/registry/src/github.com-1ecc6299db9ec823/bolero-engine-0.5.0/src/target_location.rs:136:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    nodes::behaviors::trading_post::database::tests::test_distance

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 227 filtered out

error: test failed, to rerun pass '--lib'
```

**Comment by camshaft** [comment]
Ah right... yeah this is going to be hard to root cause without a reproduction repo :)

**Comment by ckaran** [comment]
I was afraid of that! I'll see what I can do to create a miniature test repo.  That will take a few days though, I hope you don't mind.

**Comment by camshaft** [comment]
All of the examples are executed as integration tests so that would work

**Comment by ckaran** [comment]
OK, I just made PR #14.  Instructions and explanations for it are in the `README.md` that accompanies it.  Please let me know if you need anything else from me.

Also, I can't get the examples to run from the top level via `cargo test --examples`; this includes your own examples.  What command do you use to get them to run from the top level?

**Comment by camshaft** [comment]
Well that was pretty easy to find; thanks for doing that.

The [HashSet generator](https://github.com/camshaft/bolero/blob/master/bolero-generator/src/std/mod.rs#L33) loops until it arrives at the length it needs, which could be never. I actually accounted for that in the [BTreeSet generator](https://github.com/camshaft/bolero/blob/master/bolero-generator/src/alloc/mod.rs#L84) but didn't move it over.

The other issue is the HashSet generator was missing tests, which definitely would have caught the issue.

I've now added tests and refactored the collection generators a bit to avoid this problem in the future. I'll try to get a release out today.

**Comment by ckaran** [comment]
Cool, thank you! I'll try it out with my real code once you make the release.

**Comment by camshaft** [comment]
ok [`0.5.1`](https://crates.io/crates/bolero-generator/0.5.1) was just published

**Comment by ckaran** [comment]
Thank you, and while that fixed the HashSet problem, it turned up another one that causes about half my tests to fail.  I'm working on creating a new reduced test case now, I'll send you a PR shortly, and I'll start a new issue for it.
